// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qpsjevpoetfzpdklttci.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwc2pldnBvZXRmenBka2x0dGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyMDkwMTgsImV4cCI6MjA0ODc4NTAxOH0.QGTEBsgJs2jk8ZrDtEFIowrCd39aXAH11-S7uhazNHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);